package com.example.data.api

import com.example.BuildConfig
import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit
import android.util.Log

// --- Gemini API Request/Response Models ---

@JsonClass(generateAdapter = true)
data class GenerateContentRequest(
    @Json(name = "contents") val contents: List<Content>,
    @Json(name = "generationConfig") val generationConfig: GenerationConfig? = null,
    @Json(name = "systemInstruction") val systemInstruction: Content? = null
)

@JsonClass(generateAdapter = true)
data class Content(
    @Json(name = "parts") val parts: List<Part>
)

@JsonClass(generateAdapter = true)
data class Part(
    @Json(name = "text") val text: String? = null
)

@JsonClass(generateAdapter = true)
data class GenerationConfig(
    @Json(name = "responseMimeType") val responseMimeType: String? = null,
    @Json(name = "temperature") val temperature: Float? = null
)

@JsonClass(generateAdapter = true)
data class GenerateContentResponse(
    @Json(name = "candidates") val candidates: List<Candidate>?
)

@JsonClass(generateAdapter = true)
data class Candidate(
    @Json(name = "content") val content: Content?
)

// --- Song Detail Model generated by Gemini ---
@JsonClass(generateAdapter = true)
data class GeminiSongJson(
    @Json(name = "title") val title: String,
    @Json(name = "artist") val artist: String,
    @Json(name = "album") val album: String? = "Unknown Album",
    @Json(name = "durationSeconds") val durationSeconds: Int? = 180,
    @Json(name = "genre") val genre: String? = "Unknown",
    @Json(name = "releaseYear") val releaseYear: String? = "Unknown",
    @Json(name = "lyrics") val lyrics: String? = "Lyrics not available.",
    @Json(name = "trivia") val trivia: String? = "No trivia available.",
    @Json(name = "tempoBpm") val tempoBpm: Int? = 120,
    @Json(name = "mood") val mood: String? = "Energetic",
    @Json(name = "energy") val energy: Float? = 0.7f
)

@JsonClass(generateAdapter = true)
data class GeminiPlaylistJson(
    @Json(name = "name") val name: String,
    @Json(name = "description") val description: String,
    @Json(name = "songs") val songs: List<GeminiSongJson>
)

@JsonClass(generateAdapter = true)
data class GeminiDetailedSongInfo(
    @Json(name = "artistBio") val artistBio: String,
    @Json(name = "detailedBackstory") val detailedBackstory: String,
    @Json(name = "releaseDetails") val releaseDetails: String
)

fun getFallbackDetailedInfo(title: String, artist: String, album: String, releaseYear: String, trivia: String): GeminiDetailedSongInfo {
    val fallbackBio = when (artist.lowercase()) {
        "queen" -> "Queen are a British rock band formed in London in 1970. Their classic line-up was Freddie Mercury, Brian May, Roger Taylor, and John Deacon. Queen's earliest works were influenced by progressive rock, hard rock, and heavy metal, but the band gradually ventured into more conventional and radio-friendly works by incorporating further styles. They are one of the world's best-selling music artists, known for their elaborate stadium anthems and multi-layered harmonies."
        "the weeknd" -> "Abel Makkonen Tesfaye, known professionally as the Weeknd, is a Canadian singer-songwriter and record producer. Known for his sonic versatility and dark lyricism, his music explores escapism, romance, and melancholia. He is one of the world's best-selling music artists and has earned numerous awards, including four Grammy Awards, 20 Billboard Music Awards, and a Primetime Emmy nomination."
        "adele" -> "Adele Laurie Blue Adkins is an English singer-songwriter. She is known for her powerful vocals and songwriting. Adele has received numerous accolades including 16 Grammy Awards, 12 Brit Awards, an Academy Award, and a Golden Globe. Her albums are named after pivotal ages in her life."
        else -> "$artist is a highly acclaimed musical artist known for their unique contribution to the industry. Their music blends captivating melodies, thoughtful lyricism, and modern soundscapes, earning them a dedicated global fan base and critical praise for their artistic vision."
    }

    val fallbackBackstory = if (trivia.isNotEmpty() && trivia != "No fun facts available.") {
        "The story behind this track is deeply tied to its creative production. $trivia\n\nMusically, the song features a distinct sonic palette designed to evoke specific emotional wavelengths. The artist experimented with unique arrangements to bring a cinematic narrative to life, ensuring every beat and instrument serves the core theme."
    } else {
        "\"$title\" represents a pivotal artistic statement for $artist. Written during a period of intense creative exploration, the song delves into profound thematic dimensions. The lyrical structure and sonic layers were designed to create an immersive, transportive experience for listeners, blending emotional vulnerability with sonic sophistication."
    }

    val fallbackRelease = "Released as part of the album \"$album\" in $releaseYear, the track was met with enthusiastic acclaim from critics and fans alike. Its production quality and distinct arrangements highlighted $artist's dedication to sonic innovation. The song quickly found its way onto major charts and playlists globally, solidifying its place in modern music history."

    return GeminiDetailedSongInfo(
        artistBio = fallbackBio,
        detailedBackstory = fallbackBackstory,
        releaseDetails = fallbackRelease
    )
}

// --- Retrofit Service API ---
interface GeminiService {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GenerateContentRequest
    ): GenerateContentResponse
}

// --- Client Singleton ---
object GeminiClient {
    private const val TAG = "GeminiClient"
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val loggingInterceptor = HttpLoggingInterceptor().apply {
        level = HttpLoggingInterceptor.Level.BODY
    }

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .addInterceptor(loggingInterceptor)
        .build()

    private val retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL)
        .client(okHttpClient)
        .addConverterFactory(MoshiConverterFactory.create(moshi))
        .build()

    val service: GeminiService = retrofit.create(GeminiService::class.java)

    fun getMoshi(): Moshi = moshi

    /**
     * Checks if a valid API key is available in BuildConfig.
     */
    fun isApiKeyAvailable(): Boolean {
        // Gemini AI integration has been disabled in this build — always treat as unavailable
        return false
    }

    /**
     * Search any song in the world using Gemini API.
     */
    suspend fun fetchSongFromAI(query: String): GeminiSongJson? {
        Log.i(TAG, "Gemini AI disabled — fetchSongFromAI returning null for query: $query")
        return null
    }

    /**
     * Parses a playlist link or text from other apps using Gemini AI.
     * If a link is provided, it intelligently identifies or synthesizes a list of songs matching the platform or playlist style, 
     * complete with lyrics, genre, and trivia.
     */
    suspend fun parsePlaylistWithAI(source: String, input: String): GeminiPlaylistJson? {
        Log.i(TAG, "Gemini AI disabled — parsePlaylistWithAI returning null for source: $source")
        return null
    }

    /**
     * Fetch detailed artist biography, song backstory, and release details using Gemini AI.
     */
    suspend fun fetchDetailedSongInfo(title: String, artist: String, album: String, releaseYear: String): GeminiDetailedSongInfo? {
        Log.i(TAG, "Gemini AI disabled — fetchDetailedSongInfo returning fallback for $title by $artist")
        return null
    }
}
